name: Build Completed

on:
  workflow_run:
    types:
      - "completed"
    workflows:
      - "Build"

jobs:
  build_completed:
    uses: CivMC/.github/.github/workflows/gradle_publish.yml@master
    secrets: inherit
