name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
    gradle_build:
        name: Gradle Build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v3
              with:
                  java-version: '${{ inputs.java_version }}'
                  distribution: '${{ inputs.java_distribution }}'

            - name: Run Gradle Build
              uses: gradle/gradle-build-action@v2
              env:
                  CI: true
              with:
                  arguments: '${{ inputs.gradle_task }} --scan'

            - name: Upload Build Artifact
              uses: actions/upload-artifact@v3
              with:
                  name: gradle-build
                  path: '**/build/libs/*'
